
---
#change(s) for all routers
- hosts: Routers
  gather_facts: false
  connection: local
  tasks:
    - name: configure same the banner on all group Routers
      ios_banner:
        banner: login
        text: |
          This is my super banner in group [Routers]
          ...
        state: present


##############################################################
#change(s) on router1
- hosts: Router1
  gather_facts: false
  connection: local
  tasks:
    - name: configure the banner for R1
      ios_banner:
        banner: login
        text: |
          This is my super banner R1
          ...
        state: present
    #configure loopback address on R1
    #provider & lines definition
    - name: loopback interface on R1
      ios_config:
        provider: "{{provider}}" #file to define provider
        lines:
        - ip address 1.1.1.1 255.255.255.255
        - no shutdown
        parents: interface Loopback0


#change(s) on router2
- hosts: Router2
  gather_facts: false
  connection: local
  tasks:
    - name: configure the banner for R2
      ios_banner:
        banner: login
        text: |
          This is my super banner R2
          ...
        state: present

    - name: loopback interface on R2
      ios_config:
        provider: "{{provider}}"
        lines:
        - ip address 2.2.2.2 255.255.255.255
        - no shutdown
        parents: interface Loopback0

