
---
#change(s) for all routers
#- hosts: Routers #group of hosts
#  gather_facts: false #gather variables about the hosts
#  connection: local #connection: local , delegate_to: localhost, local_action
#  tasks:
#    - name: configure same the banner on all group Routers
#      ios_banner:
#        banner: login
#        text: |
#          This is my super banner in group [Routers]
#        state: present


##############################################################
#change(s) on router1
- hosts: Router1
  gather_facts: false
  connection: local
  tasks:
    - name: configure the banner for R1
      ios_banner:
        banner: login
        text: |
          This is my super banner R1
        state: present
    - name: configure loopback interface on R1
      ios_config:
        lines:
        - ip address 1.1.1.1 255.255.255.255
        - no shutdown
        parents: interface Loopback0



#change(s) on router2
- hosts: Router2
  gather_facts: false
  connection: local
  tasks:
    - name: configure the banner for R2
      ios_banner:
        banner: login
        text: |
          This is my super banner R2
        state: present
    - name: configure loopback interface on R2
      ios_config:
        lines:
        - ip address 2.2.2.2 255.255.255.255
        - no shutdown
        parents: interface Loopback0


#change(s) on router3
- hosts: Router3
  gather_facts: false
  connection: local
  tasks:
    - name: configure the banner for R3
      ios_banner:
        banner: login
        text: |
          This is my super banner R3
        state: present
    - name: configure loopback interface on R3
      ios_config:
        lines:
        - ip address 3.3.3.3 255.255.255.255
        - no shutdown
        parents: interface Loopback0


#change(s) on pc2
- hosts: PC_apache
  become: yes #sudo: yes ##old version 
  tasks:
    - name: install apache on PC2
      apt: name=apache2 update_cache=yes state=latest #update_cache=yes -> force to check if package cache is out of date and update it

